name: btp
description: "Modern Indian Farming Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2

  # UI packages
  flutter_animate: ^4.5.0
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  figma_squircle: ^0.5.3
  flutter_staggered_animations: ^1.1.1
  
  # Charts
  fl_chart: ^0.69.0
  
  # Networking
  dio: ^5.7.0
  http: ^1.2.2
  
  # Location & Connectivity
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.5
  
  # Storage & Database
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Utilities
  intl: ^0.19.0
  
  # Development tools
  flutter_screenutil: ^5.9.3
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - CSV Data/
    - CSV Data/soil_data_by_region.csv
    - CSV Data/regional_crop_calendar.csv
    - CSV Data/historical_weather_data.csv
    - CSV Data/input_costs_regional.csv
    - CSV Data/regional_configuration.json
    - CSV Data/mobile_app_database_schema.json
    - CSV Data/implementation_roadmap.json
